/*
 * Copyright (C) 2021 Pietro P.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package codicefiscale_en;

import java.time.Year;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.Scanner;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 * Controls the UI of the app, interfacing with the CodiceFiscale class to generate the fiscal code.
 * @author Pietro P.
 */
public class CodiceFiscaleUI extends javax.swing.JFrame {
    
    /**
     * Creates new form CodiceFiscaleUI
     */
    public CodiceFiscaleUI() {
        initComponents();
        try {
            initTableComune(); //initialize the jTable with the municipalities using the data from the included .csv file
            textFieldComuneUpdate(); //documentListener that updates the filter for the search in the jTable with municipalities
        } catch(Exception ex) {
            textFieldErrori.setText(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformazioniPersonali = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        labelCognome = new javax.swing.JLabel();
        textFieldCognome = new javax.swing.JTextField();
        labelSesso = new javax.swing.JLabel();
        comboBoxSesso = new javax.swing.JComboBox<>();
        labelNascita = new javax.swing.JLabel();
        labelGiorno = new javax.swing.JLabel();
        labelMese = new javax.swing.JLabel();
        labelAnno = new javax.swing.JLabel();
        comboBoxMese = new javax.swing.JComboBox<>();
        comboBoxAnno = new javax.swing.JComboBox<>();
        textFieldErrori = new javax.swing.JTextField();
        textFieldComune = new javax.swing.JTextField();
        comboBoxGiorno = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableComune = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        panelCodiceFiscale = new javax.swing.JPanel();
        labelRisultato = new javax.swing.JLabel();
        textFieldCodiceFiscale = new javax.swing.JTextField();
        buttonReset = new javax.swing.JButton();
        buttonGenera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calcolo del Codice Fiscale");
        setResizable(false);

        panelInformazioniPersonali.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informazioni personali", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        labelNome.setText("Nome:");

        labelCognome.setText("Cognome:");

        labelSesso.setText("Sesso:");

        comboBoxSesso.setMaximumRowCount(2);
        comboBoxSesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maschio", "Femmina" }));

        labelNascita.setText("Data di nascita:");

        labelGiorno.setText("Giorno");

        labelMese.setText("Mese");

        labelAnno.setText("Anno");

        comboBoxMese.setMaximumRowCount(12);
        comboBoxMese.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre" }));

        comboBoxAnno.setMaximumRowCount(10);
        comboBoxAnno.setModel(new javax.swing.DefaultComboBoxModel<>(initComboBoxAnno()));

        textFieldErrori.setEditable(false);

        comboBoxGiorno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        tableComune.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comune, Provincia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableComune.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableComune.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableComune.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableComune.setShowHorizontalLines(false);
        tableComune.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tableComune);

        jLabel1.setText("Ricerca:");

        javax.swing.GroupLayout panelInformazioniPersonaliLayout = new javax.swing.GroupLayout(panelInformazioniPersonali);
        panelInformazioniPersonali.setLayout(panelInformazioniPersonaliLayout);
        panelInformazioniPersonaliLayout.setHorizontalGroup(
            panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformazioniPersonaliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformazioniPersonaliLayout.createSequentialGroup()
                        .addComponent(textFieldErrori)
                        .addGap(147, 147, 147))
                    .addGroup(panelInformazioniPersonaliLayout.createSequentialGroup()
                        .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInformazioniPersonaliLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldComune))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInformazioniPersonaliLayout.createSequentialGroup()
                                .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCognome)
                                    .addComponent(labelNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(textFieldCognome)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInformazioniPersonaliLayout.createSequentialGroup()
                                .addComponent(labelNascita)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformazioniPersonaliLayout.createSequentialGroup()
                                .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelInformazioniPersonaliLayout.createSequentialGroup()
                                        .addComponent(labelSesso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxSesso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelInformazioniPersonaliLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(labelAnno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxAnno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelInformazioniPersonaliLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelMese)
                                            .addComponent(labelGiorno))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboBoxGiorno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboBoxMese, 0, 87, Short.MAX_VALUE))))
                                .addGap(147, 147, 147))))))
        );
        panelInformazioniPersonaliLayout.setVerticalGroup(
            panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformazioniPersonaliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSesso)
                    .addComponent(comboBoxSesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCognome)
                    .addComponent(textFieldCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNascita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformazioniPersonaliLayout.createSequentialGroup()
                        .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxGiorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelGiorno))
                        .addGap(6, 6, 6)
                        .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxMese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMese))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAnno))
                        .addGap(0, 165, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformazioniPersonaliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldComune, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(textFieldErrori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        panelCodiceFiscale.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Codice Fiscale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        labelRisultato.setText("Risultato:");

        textFieldCodiceFiscale.setEditable(false);

        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        buttonGenera.setText("Genera");
        buttonGenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGeneraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCodiceFiscaleLayout = new javax.swing.GroupLayout(panelCodiceFiscale);
        panelCodiceFiscale.setLayout(panelCodiceFiscaleLayout);
        panelCodiceFiscaleLayout.setHorizontalGroup(
            panelCodiceFiscaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodiceFiscaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCodiceFiscaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCodiceFiscaleLayout.createSequentialGroup()
                        .addComponent(labelRisultato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldCodiceFiscale, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCodiceFiscaleLayout.createSequentialGroup()
                        .addComponent(buttonGenera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonReset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCodiceFiscaleLayout.setVerticalGroup(
            panelCodiceFiscaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCodiceFiscaleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCodiceFiscaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRisultato)
                    .addComponent(textFieldCodiceFiscale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCodiceFiscaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonReset)
                    .addComponent(buttonGenera))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInformazioniPersonali, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelCodiceFiscale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInformazioniPersonali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCodiceFiscale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Prints in "textFieldCodiceFiscale" the Fiscal Code generated from the data inserted in the other fields 
     * If the data has been inserted incorrectly, the relevant error is printed in "textFieldErrori"
     * @param evt 
     */
    private void buttonGeneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGeneraActionPerformed
              
    //Fiscal Code and error text fields are reset
    textFieldErrori.setText("");
    textFieldCodiceFiscale.setText("");

    char sesso; //char that defines the sex of the person

    //assigns the correct value to "sesso" (ComboBox SelectedIndex 0 --> male, SelectedIndex 1 --> female)
    if(comboBoxSesso.getSelectedIndex() == 0) {
        sesso = 'm';
    }
    else {
        sesso = 'f';
    }

        try {
            
            if(tableComune.getSelectedRow() == -1) { //prevents the "inavild index" error to show up in the errors text field and substitutes it with a more self explaining error
                throw new Exception("Nessun comune selezionato");
            }
            
            //retrieves all of the data from the app's fields in the UI to build the fiscal code
            codiceFiscale.setCognome(textFieldCognome.getText());
            codiceFiscale.setNome(textFieldNome.getText());
            codiceFiscale.setAnno(comboBoxAnno.getSelectedIndex()+CodiceFiscale.ANNOSOGLIA);
            codiceFiscale.setMese(comboBoxMese.getSelectedIndex()+1);
            codiceFiscale.setGiorno(comboBoxGiorno.getSelectedIndex()+1);
            codiceFiscale.setSesso(sesso);
            codiceFiscale.setComune(tableComune.getValueAt(tableComune.getSelectedRow(), 0).toString().substring(0, tableComune.getValueAt(tableComune.getSelectedRow(), 0).toString().length()-4));
            codiceFiscale.setProvincia(tableComune.getValueAt(tableComune.getSelectedRow(), 0).toString().substring(tableComune.getValueAt(tableComune.getSelectedRow(), 0).toString().length()-3));

            textFieldCodiceFiscale.setText(codiceFiscale.costruisciCodiceFiscale()); //generates the fiscal code and prints it in "textFieldCodiceFiscale"
            
        } catch(Exception ecc) {
            textFieldErrori.setText(ecc.getMessage());
        }
    }//GEN-LAST:event_buttonGeneraActionPerformed

    /**
     * Resets all of the fields in the form when the "reset" button is pressed
     * @param evt 
     */
    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        
        textFieldCognome.setText("");
        textFieldNome.setText("");
        textFieldComune.setText("");
        textFieldCodiceFiscale.setText("");
        textFieldErrori.setText("");
        
        comboBoxSesso.setSelectedIndex(0);
        comboBoxGiorno.setSelectedIndex(0);
        comboBoxMese.setSelectedIndex(0);
        comboBoxAnno.setSelectedIndex(0);
        
        tableComune.clearSelection();
    }//GEN-LAST:event_buttonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CodiceFiscaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CodiceFiscaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CodiceFiscaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CodiceFiscaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        
        FlatLightLaf.install(); //sets Look and Feel "FlatLaf Light"
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodiceFiscaleUI().setVisible(true);
            }
        });
    }
    
    /**
     * Generates a Integer[] that contains all years from 1848 to the current one
     * @return Integer[] with all of the years in chronological order
     */
    private Integer[] initComboBoxAnno() {
        
        int annoCorrente = Year.now().getValue(); //current year
        Integer[] items = new Integer[annoCorrente-CodiceFiscale.ANNOSOGLIA+1]; //initialize array with correct length
        
        for (int i=0; i<items.length; i++) {
            items[i] = CodiceFiscale.ANNOSOGLIA+i; //fills the array with the years
        }
        
        return items;
    }
    
    /**
     * Generates a list with all of the municipalities present in Italy from a .csv file, and inserts them in "tableComune" (Municipality table)
     * It also initializes the RowSorter and Filter for the table, so that it's possible to search for a specific municipality
     * @throws Exception if the .csv file is not found
     */
    private void initTableComune() throws Exception {
        
        final String DELIMITATORE = ","; //value delimitator in .csv files
        Scanner input = new Scanner(CodiceFiscale.ELENCOCOMUNI);
        DefaultTableModel modello = (DefaultTableModel)tableComune.getModel(); //gets the model of the municipality table, to add more rows
        String[] output = new String[1]; //contains the text to inert at the appropriate row in the table (it's an array because jTable.addRow() accept only arrays even if single column)
        String[] linea; //contains the current line of the .csv file, split in parts

        while(input.hasNextLine()) { //reads all of the lines of the file

            linea = input.nextLine().split(DELIMITATORE); //splits the line in Municipality, Province and Municipality code

            output[0] = linea[0] + ", " + linea[1]; //formats the String to add in a table row, like this: "Municipality, Province"

            modello.addRow(output); //adds a row containing Municipality and Province to the table
        }
        
        sorter = new TableRowSorter<>(tableComune.getModel()); //creates a TableRowSorter
        tableComune.setRowSorter(sorter); //sets the sorter as the sorter for the Municipality table
    }
    
    /**
     * Whenever the text in "textFieldComune" (the search field for the Municipality table) is changed, the search fro the municipality table is updated
     */
    private void textFieldComuneUpdate() {
        
        //adds a DocumentListener to the search text field
        textFieldComune.getDocument().addDocumentListener(
                new DocumentListener() {
                    //when the text inside it is changed, run the search method
                    @Override
                    public void changedUpdate(DocumentEvent e) {
                        ricercaTableComune();
                    }
                    @Override
                    public void insertUpdate(DocumentEvent e) {
                        ricercaTableComune();
                    }
                    @Override
                    public void removeUpdate(DocumentEvent e) {
                        ricercaTableComune();
                    }
                });
    }
    
    /**
     * Using the text input in the text search field, searches and shows only the rows that contain that text input, hiding all of the other rows
     */
    private void ricercaTableComune() {
        
        RowFilter<TableModel, Integer> filtro = null; //initializes a new row filter
        
        try {
            filtro = RowFilter.regexFilter(textFieldComune.getText().toUpperCase(), 0); //shows only rows that have a correspondence to the regEx input in the search text field
        } catch (java.util.regex.PatternSyntaxException e) { //if current expression doesn't parse, don't update
        }
        sorter.setRowFilter(filtro); //the filter gets applied do the table
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGenera;
    private javax.swing.JButton buttonReset;
    private javax.swing.JComboBox<Integer> comboBoxAnno;
    private javax.swing.JComboBox<String> comboBoxGiorno;
    private javax.swing.JComboBox<String> comboBoxMese;
    private javax.swing.JComboBox<String> comboBoxSesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAnno;
    private javax.swing.JLabel labelCognome;
    private javax.swing.JLabel labelGiorno;
    private javax.swing.JLabel labelMese;
    private javax.swing.JLabel labelNascita;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRisultato;
    private javax.swing.JLabel labelSesso;
    private javax.swing.JPanel panelCodiceFiscale;
    private javax.swing.JPanel panelInformazioniPersonali;
    private javax.swing.JTable tableComune;
    private javax.swing.JTextField textFieldCodiceFiscale;
    private javax.swing.JTextField textFieldCognome;
    private javax.swing.JTextField textFieldComune;
    private javax.swing.JTextField textFieldErrori;
    private javax.swing.JTextField textFieldNome;
    // End of variables declaration//GEN-END:variables
    private TableRowSorter<TableModel> sorter;
    private CodiceFiscale codiceFiscale = new CodiceFiscale();
}